export const REGISTER_USER = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const DELETE_USER = "DELETE_USER";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";
export const DEAUTHENTICATE_USER = "DEAUTHENTICATE_USER";

export const SAVE_USER_INFO = "SAVE_USER_INFO";
export const HAS_SET_PROFILE = "HAS_SET_PROFILE";
export const HAS_NO_PROFILE = "HAS_NO_PROFILE";

export const LOGIN_FAIL = "LOGIN_FAIL";
